#!/usr/bin/env bash
#
# setup-mac.sh — macOS에서 MeetingCrew를 바로 빌드·실행 가능한 상태로 만들어주는
# 원클릭 셋업 스크립트. clone 직후 한 번만 돌리면 됩니다.
#
#   ./scripts/setup-mac.sh
#
# 이 스크립트가 하는 일:
#   1. 전제 조건 확인 (macOS, Xcode Command Line Tools)
#   2. (선택) 사용자 Development Team을 자동 감지해 xcconfig에 주입
#   3. xcodebuild -list 로 프로젝트 구조 검증
#   4. iOS Simulator 대상 빌드 스모크 테스트
#   5. macOS 대상 빌드 스모크 테스트
#   6. 최종 안내 출력

set -euo pipefail

RED="\033[31m"; GRN="\033[32m"; YEL="\033[33m"; BLD="\033[1m"; RST="\033[0m"

log()  { printf "${BLD}==>${RST} %s\n" "$*"; }
ok()   { printf "${GRN}[OK]${RST} %s\n" "$*"; }
warn() { printf "${YEL}[WARN]${RST} %s\n" "$*"; }
die()  { printf "${RED}[ERROR]${RST} %s\n" "$*" >&2; exit 1; }

PROJECT="MeetingCrew.xcodeproj"
SCHEME="MeetingCrew"
BUNDLE_ID="com.meetingcrew.app"

cd "$(dirname "$0")/.."

# ---------- 1. 전제 조건 ----------
log "Checking prerequisites..."

[ "$(uname)" = "Darwin" ] || die "이 스크립트는 macOS 전용입니다. (현재: $(uname))"

if ! xcode-select -p >/dev/null 2>&1; then
  die "Xcode Command Line Tools가 없습니다. 'xcode-select --install' 먼저 실행해주세요."
fi

if ! command -v xcodebuild >/dev/null 2>&1; then
  die "xcodebuild를 찾을 수 없습니다. Xcode를 먼저 설치해주세요."
fi

XCODE_VERSION=$(xcodebuild -version | head -1 | awk '{print $2}')
ok "Xcode ${XCODE_VERSION}"

[ -d "$PROJECT" ] || die "$PROJECT 가 없습니다. 저장소 루트에서 실행해주세요."

# ---------- 2. Development Team 자동 감지 ----------
log "Detecting signing identity..."

TEAM_ID="${DEVELOPMENT_TEAM:-}"
if [ -z "$TEAM_ID" ]; then
  # security find-identity 로 "Apple Development" 인증서 중 첫 번째 팀 ID 추출
  TEAM_ID=$(security find-identity -v -p codesigning 2>/dev/null \
    | grep -Eo "\"Apple Development: .*\(([A-Z0-9]+)\)\"" \
    | head -1 \
    | grep -Eo "\([A-Z0-9]{10}\)" \
    | tr -d "()" || true)
fi

if [ -n "$TEAM_ID" ]; then
  ok "Development Team: $TEAM_ID"
  # 로컬 xcconfig 에 주입 (pbxproj 자체는 건드리지 않음)
  mkdir -p .local
  cat > .local/LocalSigning.xcconfig <<CFG
// Auto-generated by scripts/setup-mac.sh — do NOT commit
DEVELOPMENT_TEAM = $TEAM_ID
CODE_SIGN_STYLE = Automatic
CFG
  ok "Wrote .local/LocalSigning.xcconfig"
else
  warn "Development Team을 찾지 못했습니다. 시뮬레이터/My Mac 실행은 가능하지만,"
  warn "실기기 배포 시 Xcode GUI 의 Signing & Capabilities 에서 팀을 지정해야 합니다."
fi

# ---------- 3. 프로젝트 구조 검증 ----------
log "Validating project structure..."
xcodebuild -list -project "$PROJECT" >/dev/null || die "xcodebuild -list 실패"
ok "Project is parseable"

# ---------- 4. iOS Simulator 빌드 ----------
log "Building for iOS Simulator (smoke test)..."
IOS_DEST="generic/platform=iOS Simulator"
set +e
xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -destination "$IOS_DEST" \
  -derivedDataPath build/DerivedData \
  -quiet \
  CODE_SIGNING_ALLOWED=NO \
  build
IOS_RC=$?
set -e
if [ $IOS_RC -eq 0 ]; then
  ok "iOS Simulator build succeeded"
else
  warn "iOS Simulator build failed (exit $IOS_RC). 자세한 로그는 아래 명령으로 확인:"
  warn "  xcodebuild -project $PROJECT -scheme $SCHEME -destination '$IOS_DEST' build"
fi

# ---------- 5. macOS 빌드 ----------
log "Building for My Mac (smoke test)..."
MAC_DEST="generic/platform=macOS"
set +e
xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -destination "$MAC_DEST" \
  -derivedDataPath build/DerivedData \
  -quiet \
  CODE_SIGNING_ALLOWED=NO \
  build
MAC_RC=$?
set -e
if [ $MAC_RC -eq 0 ]; then
  ok "macOS build succeeded"
else
  warn "macOS build failed (exit $MAC_RC)."
fi

# ---------- 6. 최종 안내 ----------
echo
echo "================================================================"
echo " MeetingCrew setup complete"
echo "================================================================"
echo
echo "다음 단계:"
echo "  1. Xcode 에서 프로젝트 열기"
echo "       open $PROJECT"
echo
echo "  2. 상단 스킴 선택 옆에서 실행 타겟 고르기"
echo "       - My Mac"
echo "       - iPhone 15 Simulator (또는 다른 iOS 17+ 시뮬레이터)"
echo
echo "  3. Cmd+R 로 실행"
echo
echo "  4. 앱 내 톱니바퀴 아이콘 → Claude API Key 입력 → 연결 테스트 → 저장"
echo
echo "  5. 녹음 시작 → 마이크·음성인식 권한 허용 → 한국어로 회의 진행"
echo
if [ $IOS_RC -ne 0 ] || [ $MAC_RC -ne 0 ]; then
  echo "일부 스모크 빌드가 실패했습니다. 위 로그를 확인하거나,"
  echo "문제가 계속되면 작성자에게 xcodebuild 로그 전체를 공유해주세요."
fi
